# Why Numpy

1 Fast

2 Memory efficient

3 Intutive syntax

In [ ]:
#!conda install numpy
#!pip install numpy

In [1]:
import numpy as np
# import sys

In [3]:
#create array
arr = np.array([1,2,3])
arr1 = np.array([10000000,898989898,35656566])
print(arr,arr1)
print("total elemets =",arr.size,arr1.size)
print("size of each item =",arr.itemsize,arr1.itemsize)
print("Data type of each element=",type(arr[0]),type(arr1[0]))

[1 2 3] [ 10000000 898989898  35656566]
total elemets = 3 3
size of each item = 8 8
Data type of each element= <class 'numpy.int64'> <class 'numpy.int64'>


In [5]:
arr = np.array([1,2,3])
arr*4

array([ 4,  8, 12])

In [6]:
arr = np.array([1,2,3])
arr%2 
# [ 1 2 3]

array([1, 0, 1])

In [7]:
arr = np.array([1,2,3])
arr*arr # Element wise multiplication

array([1, 4, 9])

In [12]:
# WAP to have one array Basic salary and another array bonus percentage 
# of every employee.
# Print total salary of every employee
basic_sal = np.array([100000,223456,3455674])
bonus_per = np.array([30,45,10])
total_sal = basic_sal + (basic_sal * bonus_per) / 100
print(total_sal)

[ 130000.   324011.2 3801241.4]


In [15]:
arr1 = np.arange(10,30,2)
# start < end when step +ve, 
# start > end when step -ve 
arr2=np.arange(10,-3,-1) 
print(arr1,arr2)

[10 12 14 16 18 20 22 24 26 28] []


In [ ]:
np.arange(40.5,29.9,-0.3)#,dtype = float)

array([40.5, 40.2, 39.9, 39.6, 39.3, 39. , 38.7, 38.4, 38.1, 37.8, 37.5,
       37.2, 36.9, 36.6, 36.3, 36. , 35.7, 35.4, 35.1, 34.8, 34.5, 34.2,
       33.9, 33.6, 33.3, 33. , 32.7, 32.4, 32.1, 31.8, 31.5, 31.2, 30.9,
       30.6, 30.3, 30. ])

In [18]:
np.arange(10,30.3,0.7,dtype = float) 
# incase of floating point step 
# End value is inclusive :: because of rounding off effect

array([10. , 10.7, 11.4, 12.1, 12.8, 13.5, 14.2, 14.9, 15.6, 16.3, 17. ,
       17.7, 18.4, 19.1, 19.8, 20.5, 21.2, 21.9, 22.6, 23.3, 24. , 24.7,
       25.4, 26.1, 26.8, 27.5, 28.2, 28.9, 29.6, 30.3])

In [ ]:
np.arange(10.2,20.2,0.2) # Not always..

array([10.2, 10.4, 10.6, 10.8, 11. , 11.2, 11.4, 11.6, 11.8, 12. , 12.2,
       12.4, 12.6, 12.8, 13. , 13.2, 13.4, 13.6, 13.8, 14. , 14.2, 14.4,
       14.6, 14.8, 15. , 15.2, 15.4, 15.6, 15.8, 16. , 16.2, 16.4, 16.6,
       16.8, 17. , 17.2, 17.4, 17.6, 17.8, 18. , 18.2, 18.4, 18.6, 18.8,
       19. , 19.2, 19.4, 19.6, 19.8, 20. ])

In [ ]:
arr1+arr2 # + , -,  *,  /

array([15, 23, 36])

In [ ]:
arr3=np.arange(10)
print(arr1)
print(arr3)
arr1+arr3

[15 22 34]
[0 1 2 3 4 5 6 7 8 9]


ValueError: ignored

# Assignment 

Given array of marks out of hundred for 5 students 

Find percentile of each student
percentile = marks / max_marks *100

In [ ]:
a1 = np.array([90,87,85,95,90])
print(a1.max())
per = a1 / a1.max() * 100
print(per)
per1 = a1 / max(a1) * 100
print(per1)

95
[ 94.73684211  91.57894737  89.47368421 100.          94.73684211]
[ 94.73684211  91.57894737  89.47368421 100.          94.73684211]


In [ ]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [ ]:
np.array([1+67j, 2, 3], dtype=complex)
# All data types in numpy
#https://numpy.org/devdocs/user/basics.types.html

array([1.+67.j, 2. +0.j, 3. +0.j])

# Functions to create default array

*empty_like*
Return an empty array with shape and type of input.

*ones_like*
Return an array of ones with shape and type of input.

*zeros_like*
Return an array of zeros with shape and type of input.

*full_like*
Return a full array with the same shape and type as a given array.

*empty*
Return a new uninitialized array.

*ones*
Return a new array setting values to one.

*zeros*
Return a new array setting values to zero.

*full*
Return a new array of given shape and type, filled with fill_value.

In [ ]:
np.random.randint(1,500,5) # psuedo random number genrator

array([277, 414, 167, 495, 117])

In [ ]:
my_rand = np.random.rand(6) # values between 0 to 1
print(my_rand)
# Create random array containing numbers between 10 to 20 with total 10 elements

[0.06736142 0.53206715 0.11228259 0.021103   0.7270202  0.07125422]


In [22]:
np.linspace(1,6,6) # Equal distant numbers

array([1., 2., 3., 4., 5., 6.])

In [24]:
arr = np.array([[1, 2], [3, 4],[2,3],[6,7]])
print(arr)
print(arr.shape)
print(arr.reshape(2,4)) #resize()
print(arr.ravel()) # Convert multi dim array to single dim array #flattern()
print(arr) # original array is intact, only copies are returned by operations

[[1 2]
 [3 4]
 [2 3]
 [6 7]]
(4, 2)
[[1 2 3 4]
 [2 3 6 7]]
[1 2 3 4 2 3 6 7]
[[1 2]
 [3 4]
 [2 3]
 [6 7]]


In [ ]:
arr = arr.reshape(2,4)
print(arr)

[[1 2 3 4]
 [2 3 6 7]]


In [ ]:
print(arr)
print(arr.sum())
print(arr.sum(axis=0),arr.sum(axis=1))

[[1 2]
 [3 4]
 [2 3]
 [6 7]]
28
[12 16] [ 3  7  5 13]


In [ ]:
print(arr.sum.__doc__)

a.sum(axis=None, dtype=None, out=None, keepdims=False, initial=0, where=True)

    Return the sum of the array elements over the given axis.

    Refer to `numpy.sum` for full documentation.

    See Also
    --------
    numpy.sum : equivalent function


In [ ]:
print(arr.sum(axis=0),arr.sum(axis=0,keepdims=True))

[12 16] [[12 16]]


In [ ]:
#Slicing is same as lists
arr = np.array([[1, 2], [3, 4],[2,3],[6,7]])
print(arr)
print("arr[1:3,0]", arr[1:,1]) # arr[ slice dim1, slice dim2, ... ,slice dimn]
print(arr[2,1])

[[1 2]
 [3 4]
 [2 3]
 [6 7]]
arr[1:3,0] [4 3 7]
3


# Write a Program to create array of 4 rows and 3 columns
# Print all elements of rows atrting from 2 to 4 and columns 1st to 2rd.


In [25]:
# Write a Program to create array of 4 rows and 3 columns
# Print all elements of rows starting from 2 to 4 and columns 1st to 2rd.
arr1 = np.arange(100,112)
arr1 = arr1.reshape(4,3)
print(arr1)
print(arr1[2:5 , 1:3 ]) # --> 1,2
# for rowno in range(4):
#   for colno in range(3):
#     print("rowno = ", rowno, " colno= ", colno , " elem = ", arr1[rowno,colno])

[[100 101 102]
 [103 104 105]
 [106 107 108]
 [109 110 111]]
[[107 108]
 [110 111]]


In [27]:
print(arr.shape)
for x in arr:
  print(x)

(4, 2)
[1 2]
[3 4]
[2 3]
[6 7]


In [ ]:
type(arr)

numpy.ndarray

In [ ]:
for e in arr.flatten(): # arr.flat is iterator , 
                        # vs arr.flatten return a copy of flat arr
  print(e)

1
2
3
4
2
3
6
7


In [ ]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr)
print(arr.shape)
for x in np.nditer(arr):
 print(x)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
1
2
3
4
5
6
7
8


In [ ]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for i, x in np.ndenumerate(arr):
 print(i, x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(1, 0, 0) 5
(1, 0, 1) 6
(1, 1, 0) 7
(1, 1, 1) 8


In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
mask = arr<5
print(mask)

[[ True  True]
 [ True  True]
 [False False]
 [False False]]


In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print(arr[arr%2==0])
mask = arr%2==0
print(arr[mask])

[2 4 6 8]
[2 4 6 8]


In [ ]:
# WAP to create 3 by 3 matrix
# select all elements which are divisible by 11
# Print the sum of square of all the elements
arr1 = np.array([[11,23,45],[55,77,88],[87,101,121]])
mask = (arr1%11 == 0)
print(mask)
c = arr1[mask]**2
c = arr1[(arr1%11 == 0)]**2
print(sum(c))

[[ True False False]
 [ True  True  True]
 [False False  True]]
31460


In [ ]:
# Indexing based on conditions
# Some problem solving based on numpy

In [ ]:
# WAP to simulate a feed forward operation in a single neuron
I = np.arange(12)
W = np.arange(12,24)
m = I*W

print(I)
print(W)
print(m)
X = sum(m)
print(X)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[12 13 14 15 16 17 18 19 20 21 22 23]
[  0  13  28  45  64  85 108 133 160 189 220 253]
1298


In [ ]:
import numpy as np
# import math
def neuron(I,W):
    X=sum(I*W)
    y = (1/(1+(np.exp(-X))))
    return y
I=np.array([1,1,2,3,4])
W=np.array([2,2,2,2,2])
output=neuron(I,W)
print(output)


0.9999999997210531
